public class kiran {
 //   public string hello{set;get;}
    public Account cs{set;get;}
    public kiran(){
       // hello='kiran';
    }
    public pageReference nayak(){
        pageReference p=new pageReference('/apex/NewAndExisting');
        return p;
    }
    public pageReference ammu(){
        pageReference P=new pageReference('/apex/myControllervf');
        return p;
    }
    public void  hello(){
        insert cs;
        
    }
    
}